name: Paranoia
description: >
  Scan your Docker images' CA's
inputs:
  action:
    description: Which Paranoia action do you want to take. |
      Available options are `validate`, `export`, `inspect`
    required: false
    default: validate
  target_tar:
    description: Thing to inspect. Should be on the format `file://<file>`
    required: true
  paranoia_file:
    description: |
      File containing the required, forbidden or allowed CA's
    default: ".paranoia.yaml"
    required: false


runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.action }}
    - ${{ inputs.target_tar }}
