apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod
spec:
  containers:
  - name: sleeper
    image: registry.k8s.io/coredns/coredns:v1.11.3
    imagePullPolicy: IfNotPresent
    command: ["sleep", "40000"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod2
spec:
  containers:
  - name: sleeper
    image: registry.k8s.io/coredns/coredns:v1.11.3
    imagePullPolicy: IfNotPresent
    command: ["sleep", "40000"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  restartPolicy: Never
