{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "paranoia.fullname" . }}
  {{- if .Values.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "paranoia.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.metrics.serviceMonitor.namespaceSelector | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "paranoia.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.service.name }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
